### ISSUE TITLE
Add mosaic restriction endpoints to the schema

### ISSUE THREAD

**Issue by Vektrat** [nemtech/nem2-openapi#6]

**Comment by dgarcia360** [comment]
@Vektrat @martinayora An initial list of endpoints we could have to interact with [Mosaic Restrictions](http://nemtech.github.io/concepts/mosaic-restrictions.html). Could you make a PR with the final specification? Please, review the endpoints structure and list any missing additional endpoint do you think should we have.

**GlobalMosaicRestriction endpoints**

1. **GET** ``/mosaic/{mosaicId}/restrictions``

Returns an array of global mosaic restrictions assigned to the mosaic. Ideally paginated and orderable by key and type.

**AddressMosaicRestriction endpoints**

I propose to organize address mosaic restrictions under mosaics rather than accounts to avoid conflicts with account restrictions endpoints. AccountId stands for address or publicKey. If only address is possible, replace ``account/{accountId}/`` for ``../address/{address}``.

2. **GET** ``/mosaic/{mosaicId}/restrictions/account/{accountId}/``

Returns array of address mosaic restrictions for the given a ``mosaicId`` and ``targetAddress``. Ideally paginated and orderable by key.

Extra: We could have as well POST methods (/mosaic/restrictions and /mosaic/{mosaicId}/restrictions) to get different responses the same call, as we are doing with account restrictions.

**Comment by dgarcia360** [comment]
@Vektrat @martinayora Could you please update the swagger file with the complete specification? Thanks!

@rg911 @fboucquez Please, review if these initial endpoints descriptions fit your needs or if would you like to add/change them before they are implemented.

**Comment by Vektrat** [comment]
yes, we prefer to wait until we are mid development so that we don't go back on our words afterwards, just like with metadata

**Comment by martinayora** [comment]
The resulting endpoints would be as follows:

To retrieve **only mosaic global restrictions**:

1 - GET     _/mosaic/{mosaicId}/restrictions_
2 - POST    _/mosaic/restrictions_               ( body = [mosaicIds] )

To retrieve **only mosaic address restrictions**:

3 - GET     _/mosaic/{mosaicId}/restrictions/account/{accountId}_
4 - POST    _/mosaic/{mosaicId}/restrictions_    ( body = [accountIds] )

I think the post method will lead to confusion. Because the same path "_/mosaic/{mosaicId}/restrictions_" will return global restrictions in GET, but address restrictions in POST. Maybe we can change the path sligthly or leave aside the post methods for now.

Is there a way to get all mosaic restrictions (both global and address) given a mosaicId? Should it exist, does it make sense?  @dgarcia360 @Vektrat @rg911 @fboucquez

**Comment by rg911** [comment]
original proposal seems okay. the `/mosaic/{mosaicId}/restrictions` GET and POST should use the same endpoint, since it's REST don't think we need to introduce new endpoints specific for POST.

**Comment by martinayora** [comment]
As expected  _**/mosaic/{mosaicId}/restrictions**_ endpoint is giving some issues in openApi.

@rg911 suggested this new endpoints:

- /mosaic/{mosaicId}/restrictions/global
- /mosaic/restrictions/global
- /mosaic/{mosaicId}/restrictions/account/{accountId}
- /mosaic/{mosaicId}/restrictions/address

I think that **.../account/{accountId}** in third endpoint should be **.../address/{accountId}** even if the following parameter is accountId, because we are requesting address restrictions. A part from that I don't see any problems on changing them.

Can you validate these changes @dgarcia360 @Vektrat @fboucquez ?
Or is it possible to fix it in openApi whithout changing the endpoints?

**Comment by Vektrat** [comment]
we will change endpoint topology to the following:
```
/restrictions/account/
/restrictions/account/{id}
/restrictions/mosaic
/restrictions/mosaic/{id}
/restrictions/mosaic/{id}/address/{accountId}
```
the suggestions so far were troublesome and confusing, and we are not asking for mosaics or accounts in the end, but for restrictions, so this seems to be the most adequate
