### ISSUE TITLE
3 numbers versions

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-openapi#65]
The project https://github.com/NEMStudios/nem2-open-api-generator generates maven and npm packages for the Java and TS SDKs. 

The version of the generated artifacts must match the version of the Open API spec. You can tell exactly what version of the open API of the clients are generated from, and by extension, the Open API version the SDKs support.

Maven supports multiple number versions but NPM complains if there are more than 2 dots in a version (if there are just numbers). 

The current version of the spec is 0.7.20.6. https://github.com/nemtech/nem2-openapi/blob/master/spec/info.yml#L1

We need to touch the generated NPM package version calling it something different like 0.7.20-beta.6

https://www.npmjs.com/package/nem2-sdk-openapi-typescript-node-client

Could it be possible to use a simple 3 numbers version in the spec like 0.7.21 and update the minor version with every merged change?

CC: @dgarcia360 @rg911

**Comment by dgarcia360** [comment]
The API info version follows catapult-rest version number, that's why it has 
4 numbers. See https://github.com/nemtech/catapult-rest/blob/ce5d6dc245b9f664ff5273d32f1d3abd00d4423f/catapult-sdk/package.json

To fix it temporarily the npm issue, we could change the version number to ``0.7.20-beta.6`` @fboucquez what do you think?

Nevertheless, I also believe that would be better to follow SemVer and use 3 numbers.  I'm not too concerned because rest devs will probably remove this fourth number when they consider the package reaches the state to be tagged in a new release here https://github.com/nemtech/catapult-rest/releases @martinayora @Vektrat 

Still, it would be better to tag the incremental builds as 0.7.21-beta.N (next), since 0.7.20 has already been tagged.

**Comment by fboucquez** [comment]
I prefer 3 numbers version but I understand you don't want to burn a version.

Also, it may be possible that a version of rest is changed but it doesn't need a change in the open API or the SDKs. Something similar to an Open API fix. The fix of https://github.com/nemtech/nem2-openapi/issues/66 won't require a rest release as it's just adding a missing value that exist in rest.

But for example, if 66 gets fixed, what would it be the version in open API?

**Comment by dgarcia360** [comment]
I see your point. What we could do is to tag nem2-open-api spec as ``0.7.21-N``, where N indicates the open-api version within the release.

**Comment by dgarcia360** [comment]
Good point, I see two options: 

A) The rest repo starts using the second number (minor release) when new functionality is added, and we keep the third one for patches/builds. Then, open-api can and rest repo share the first two numbers, but the third one is independent per repo.

B) Start tagging nem2-open-api spec as 0.7.21-N, where N indicates the open-api version within the release.

I prefer the first option (A),  but I want to hear your thoughts to make sure we aligned @Vektrat @martinayora @fboucquez

**Comment by fboucquez** [comment]
@rg911

**Comment by Vektrat** [comment]
i've been bringing this to the community/team for months/years already i think, and no consensus was reached, hence why i unilaterally went with the 4th number, which so far has proven extremely useful when handling reports by users (easier to spot invalid reports, and to spot issues this way)

ideally, i'd prefer 3 numbers as well, with 2nd increasing with features and 3rd for random fixes *but* there are two factors here which are the reason why i haven't touched those:

1) i'm not handling builds, so i preferred not to meddle with the versioning to avoid impacting whoever is handling builds atm (nate i guess)
2) as far as i know, it was agreed by the team (or at least it has been working like this until now), that the REST version number would be kind of linked to other projects' version numbers (i can't recall if SDKs, or core, or both, but i also recall recent wishes of doing so) - i don't see any good enough reason to do that, and it adds a lot of limitations to the project, such as this one, because the REST project loses control on its own versioning system since it kind of depends on other projects - this is why i kind of was forced to add a fourth number to the project, so that it can track independent status

**Comment by fboucquez** [comment]
I agree Open API generated clients, Open API and Rest need an independent last number for bug fixes/improvements, etc. I would be happy with the fourth number, the only issue is NPM repo complains about it. Maybe making the last number a dash (-) would good enough for everybody (at least open api and generated clients)?

**Comment by Vektrat** [comment]
> I agree Open API generated clients, Open API and Rest need an independent last number for bug fixes/improvements, etc. I would be happy with the fourth number, the only issue is NPM repo complains about it. Maybe making the last number a dash (-) would good enough for everybody (at least open api and generated clients)?

this is a question for whoever is in charge of builds and version naming, i'm not sure if it could affect other scripts or whatever i may not know about, this is the same reason why i went for the 4th - either way, the best solution from my point of view would be that each project has independent versioning (from, at least, for the 2nd and the 3rd number), having related versioning is more troublesome than helpful, this is why there are compatibility version matrices and lists

**Comment by dgarcia360** [comment]
Since the _nem2-openapi_ describes catapult-rest, the version number in``info.yml`` should be equal to the latest rest version displayed [here](https://github.com/nemtech/nem2-openapi/blob/master/spec/info.yml#L1).

To have independent versioning for _nem2-open-api_ (which makes sense), we could use the [package.json](https://github.com/nemtech/nem2-openapi/blob/master/package.json#L3) version to have a totally different ``major.minor.patch`` for this package. Would this work for you? @fboucquez @rg911

**Comment by dgarcia360** [comment]
Have been reading more about the topic and finally we'll have **independent version numbers** between _nem2-open-api_ and _catapult-rest_. 

In the official OpenAPI spec it's mentioned that [the version number should correspond to the API spec and not to the API implementation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#info-object). 

We could use the ``description`` property to indicate which is the corresponding _catapult-rest_ version.

**Comment by fboucquez** [comment]
Hi @dgarcia360 , I agree with having an independent version.

**Comment by Vektrat** [comment]
it's for the best, as you said you can add a "comment" somewhere with the latest supported version of API if you think it helps - each project should have it's own independent versioning
